---
language: node_js
node_js:
  - 11
  - 10
  - 8
os:
  - linux
  - osx
  - windows
cache: npm
script:
  - npm run build
  - npm test
after_success:
  - >
    test $TRAVIS_NODE_VERSION = '11' &&
    test $TRAVIS_OS_NAME = 'linux' &&
    npm run test-integration
